version: "3.8"

services:
  promote-ayutthaya:
    build: .
    container_name: promote-ayutthaya
    restart: always
    env_file:
      - .env
    environment:
      - RUN_MODE=${RUN_MODE:-daemon}
      - TIMEZONE=${TIMEZONE:-Asia/Bangkok}
      - WEB_DASHBOARD=${WEB_DASHBOARD:-true}
      - WEB_PORT=8000
      - PUBLIC_URL=https://${DOMAIN}
    networks:
      - webnet

  caddy:
    image: caddy:2.7
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - webnet
    depends_on:
      - promote-ayutthaya

networks:
  webnet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: