version: "3.8"

services:
  promote-ayutthaya:
    build: .
    container_name: promote-ayutthaya
    restart: always
    env_file:
      - .env
    environment:
      # Fallbacks if .env not provided for some vars
      - RUN_MODE=daemon
      - TIMEZONE=${TIMEZONE:-Asia/Bangkok}
      - POST_INTERVAL_SECONDS=${POST_INTERVAL_SECONDS:-1}
      - COLLECT_INTERVAL_MINUTES=${COLLECT_INTERVAL_MINUTES:-1}
      - GENERATE_CONTENT=${GENERATE_CONTENT:-true}
      - SENDER_NAME=${SENDER_NAME:-จัสมินชอบกินแซลมอน}
      - ENABLE_ADS=${ENABLE_ADS:-true}
      - ADS_SIMULATION=${ADS_SIMULATION:-false}
      - PROVIDERS=${PROVIDERS:-twitter,facebook,linkedin,line,telegram,discord,instagram,reddit,tiktok,mastodon}
      - WEB_DASHBOARD=${WEB_DASHBOARD:-true}
      - WEB_PORT=${WEB_PORT:-8000}
      # Real API mode by default (no simulation)
      - SIMULATE_ALL_PROVIDERS=${SIMULATE_ALL_PROVIDERS:-false}
      - SIMULATE_ON_ERROR=${SIMULATE_ON_ERROR:-false}
    ports:
      - "8000:8000"
    volumes:
      - .:/app