version: "3.8"

services:
  promote-ayutthaya:
    build: .
    container_name: promote-ayutthaya
    restart: always
    env_file:
      - .env
    environment:
      # Fallbacks if .env not provided for some vars
      - RUN_MODE=daemon
      - TIMEZONE=${TIMEZONE:-Asia/Bangkok}
      - POST_INTERVAL_SECONDS=${POST_INTERVAL_SECONDS:-30}
      - COLLECT_INTERVAL_MINUTES=${COLLECT_INTERVAL_MINUTES:-2}
      - GENERATE_CONTENT=${GENERATE_CONTENT:-true}
      - SENDER_NAME=${SENDER_NAME:-Bee&Bell}
      - LIVE_PROMO=${LIVE_PROMO:-true}
      - LIVE_LINK=${LIVE_LINK:-https://vt.tiktok.com/ZSHWWv19QQTPo-eKZtG/}
      - LIVE_ADS_OBJECTIVE=${LIVE_ADS_OBJECTIVE:-WEBSITE_CLICKS}
      - ENABLE_ADS=${ENABLE_ADS:-true}
      - ADS_SIMULATION=${ADS_SIMULATION:-false}
      - PROVIDERS=${PROVIDERS:-twitter,facebook,linkedin,line,telegram,discord,instagram,reddit,tiktok}
    volumes:
      - .:/app