version: "3.8"

services:
  promote-ayutthaya:
    build: .
    container_name: promote-ayutthaya
    restart: always
    env_file:
      - .env
    environment:
      # Fallbacks if .env not provided for some vars
      - RUN_MODE=daemon
      - TIMEZONE=${TIMEZONE:-Asia/Bangkok}
      - POST_INTERVAL_SECONDS=${POST_INTERVAL_SECONDS:-60}
      - COLLECT_INTERVAL_MINUTES=${COLLECT_INTERVAL_MINUTES:-5}
      - GENERATE_CONTENT=${GENERATE_CONTENT:-true}
      - SENDER_NAME=${SENDER_NAME:-Bee&Bell}
      - ENABLE_ADS=${ENABLE_ADS:-true}
      - ADS_SIMULATION=${ADS_SIMULATION:-false}
      - PROVIDERS=${PROVIDERS:-twitter,facebook,linkedin,line,telegram,discord,instagram,reddit,tiktok}
      - WEB_DASHBOARD=${WEB_DASHBOARD:-true}
      - WEB_PORT=${WEB_PORT:-8000}
    ports:
      - "8000:8000"
    volumes:
      - .:/app